name: Update README.md

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update README.md
        run: |
          pip3 install lxml requests
          python3 update.py
      - name: Upload
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update README"